#!/usr/bin/env python3
"""
Send Real Test Emails for Receipt Processing System
This script sends actual emails with PDF attachments to test the email_ingestor_enhanced.py system.
"""

import os
import tempfile
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from email.utils import formataddr
from datetime import datetime
from test_db_receipt_update import create_test_pdf
from config import EmailConfig

def create_real_pdf_receipt(bl_number, amount, payment_date=None):
    """Create a realistic PDF receipt for testing"""
    if payment_date is None:
        payment_date = datetime.now().strftime("%Y-%m-%d")
    
    content = f"""
PAYMENT RECEIPT

Receipt Number: RCP-{bl_number}-{datetime.now().strftime('%Y%m%d%H%M')}
Date: {payment_date}
Time: {datetime.now().strftime('%H:%M:%S')}

Bill of Lading: {bl_number}
Amount Paid: ${amount:,.2f}
Payment Method: Bank Transfer

Transaction Details:
- CTN Fee: ${amount * 0.6:,.2f}
- Service Fee: ${amount * 0.4:,.2f}
- Total: ${amount:,.2f}

Status: PAID
Reference: {bl_number}-{datetime.now().strftime('%Y%m%d')}

This is an official payment receipt for logistics services.
Please retain this document for your records.

Generated by: IQS Trade System
    """
    
    return content

def send_email_with_pdf(to_email, subject, body, pdf_content, pdf_filename):
    """Send email with PDF attachment"""
    
    # Check email configuration
    if not all([
        EmailConfig.SMTP_SERVER,
        EmailConfig.SMTP_PORT,
        EmailConfig.SMTP_USERNAME,
        EmailConfig.SMTP_PASSWORD,
        EmailConfig.FROM_EMAIL
    ]):
        raise ValueError("SMTP configuration incomplete. Check environment variables.")
    
    # Create message
    msg = MIMEMultipart()
    msg['From'] = formataddr(('Test Payment System', EmailConfig.FROM_EMAIL))
    msg['To'] = to_email
    msg['Subject'] = subject
    
    # Add body
    msg.attach(MIMEText(body, 'plain'))
    
    # Create PDF attachment
    pdf_path = create_test_pdf(pdf_content, pdf_filename)
    
    with open(pdf_path, 'rb') as attachment:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(attachment.read())
    
    encoders.encode_base64(part)
    part.add_header(
        'Content-Disposition',
        f'attachment; filename= {pdf_filename}'
    )
    
    msg.attach(part)
    
    # Send email
    try:
        with smtplib.SMTP(str(EmailConfig.SMTP_SERVER), int(EmailConfig.SMTP_PORT)) as server:
            server.starttls()
            server.login(str(EmailConfig.SMTP_USERNAME), str(EmailConfig.SMTP_PASSWORD))
            server.send_message(msg)
        
        print(f"✅ Email sent successfully to: {to_email}")
        print(f"   Subject: {subject}")
        print(f"   PDF: {pdf_filename}")
        
        # Clean up temporary PDF
        try:
            os.remove(pdf_path)
        except:
            pass
            
        return True
        
    except Exception as e:
        print(f"❌ Failed to send email: {str(e)}")
        return False

def send_text_only_email(to_email, subject, body):
    """Send text-only email (will generate PDF in email_ingestor)"""
    
    if not all([
        EmailConfig.SMTP_SERVER,
        EmailConfig.SMTP_PORT,
        EmailConfig.SMTP_USERNAME,
        EmailConfig.SMTP_PASSWORD,
        EmailConfig.FROM_EMAIL
    ]):
        raise ValueError("SMTP configuration incomplete. Check environment variables.")
    
    try:
        msg = MIMEMultipart()
        msg['From'] = formataddr(('Test Payment System', EmailConfig.FROM_EMAIL))
        msg['To'] = to_email
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain'))
        
        with smtplib.SMTP(str(EmailConfig.SMTP_SERVER), int(EmailConfig.SMTP_PORT)) as server:
            server.starttls()
            server.login(str(EmailConfig.SMTP_USERNAME), str(EmailConfig.SMTP_PASSWORD))
            server.send_message(msg)
        
        print(f"✅ Text email sent successfully to: {to_email}")
        print(f"   Subject: {subject}")
        return True
        
    except Exception as e:
        print(f"❌ Failed to send email: {str(e)}")
        return False

def send_all_test_emails(target_email):
    """Send all test email scenarios"""
    
    print("📧 Sending Real Test Emails for Receipt Processing System")
    print("=" * 70)
    print(f"Target Email: {target_email}")
    print("=" * 70)
    
    # Test 1: Valid BL - Text-based receipt (NYC220)
    print("\n📧 Test 1: Valid BL - Text-based Receipt (NYC220)")
    print("-" * 50)
    subject = "Payment Receipt - NYC220"
    body = """
Dear Sir/Madam,

Please find our payment receipt for Bill of Lading NYC220.

Payment Details:
- BL Number: NYC220
- Amount Paid: $700.00
- Payment Date: August 1, 2025
- Payment Method: Bank Transfer

Best regards,
Customer Service
    """
    send_text_only_email(target_email, subject, body)
    
    # Test 2: Valid BL - PDF-based receipt (NYC221)
    print("\n📧 Test 2: Valid BL - PDF-based Receipt (NYC221)")
    print("-" * 50)
    subject = "Payment Confirmation - NYC221"
    body = "Please find attached the payment receipt for BL NYC221."
    pdf_content = create_real_pdf_receipt("NYC221", 675.0)
    send_email_with_pdf(target_email, subject, body, pdf_content, "receipt_nyc221.pdf")
    
    # Test 3: Valid BL - Mixed content (NYC223)
    print("\n📧 Test 3: Valid BL - Mixed Content (NYC223)")
    print("-" * 50)
    subject = "Payment for NYC223"
    body = """
Payment confirmation for Bill of Lading NYC223.

Amount: $675.00
Date: August 1, 2025
Reference: NYC223-001

Receipt attached.
    """
    pdf_content = create_real_pdf_receipt("NYC223", 675.0)
    send_email_with_pdf(target_email, subject, body, pdf_content, "receipt_nyc223.pdf")
    
    # Test 4: Invalid BL - Text-based (NYC224)
    print("\n📧 Test 4: Invalid BL - Text-based Receipt (NYC224)")
    print("-" * 50)
    subject = "Payment for NYC224"
    body = "Payment of $500 for BL NYC224"
    send_text_only_email(target_email, subject, body)
    
    # Test 5: Invalid BL - PDF-based (NYC225)
    print("\n📧 Test 5: Invalid BL - PDF-based Receipt (NYC225)")
    print("-" * 50)
    subject = "Payment Receipt - NYC225"
    body = "Payment receipt for BL NYC225 attached."
    pdf_content = create_real_pdf_receipt("NYC225", 600.0)
    send_email_with_pdf(target_email, subject, body, pdf_content, "receipt_nyc225.pdf")
    
    # Test 6: Underpayment - Valid BL (NYC220)
    print("\n📧 Test 6: Underpayment - Valid BL (NYC220)")
    print("-" * 50)
    subject = "Partial Payment - NYC220"
    body = "Partial payment of $650 for BL NYC220"
    send_text_only_email(target_email, subject, body)
    
    # Test 7: Overpayment - Valid BL (NYC221)
    print("\n📧 Test 7: Overpayment - Valid BL (NYC221)")
    print("-" * 50)
    subject = "Overpayment - NYC221"
    body = "Payment of $700 for BL NYC221 (includes extra amount)"
    pdf_content = create_real_pdf_receipt("NYC221", 700.0)
    send_email_with_pdf(target_email, subject, body, pdf_content, "receipt_nyc221_overpayment.pdf")
    
    # Test 8: Multiple BLs in one email
    print("\n📧 Test 8: Multiple BLs in One Email")
    print("-" * 50)
    subject = "Bulk Payment - Multiple BLs"
    body = """
Bulk payment for multiple bills:

BL NYC220: $700
BL NYC221: $675

Total: $1,375
    """
    send_text_only_email(target_email, subject, body)
    
    print("\n" + "=" * 70)
    print("🎉 All test emails sent!")
    print("📧 Check your email inbox for the test messages.")
    print("🔍 Monitor the email_ingestor_enhanced.py logs to see processing results.")
    print("=" * 70)

def send_single_test_email(target_email, test_number):
    """Send a single test email"""
    
    test_scenarios = {
        1: {
            "name": "Valid BL - Text-based Receipt (NYC220)",
            "subject": "Payment Receipt - NYC220",
            "body": """
Dear Sir/Madam,

Please find our payment receipt for Bill of Lading NYC220.

Payment Details:
- BL Number: NYC220
- Amount Paid: $700.00
- Payment Date: August 1, 2025
- Payment Method: Bank Transfer

Best regards,
Customer Service
            """,
            "pdf": None
        },
        2: {
            "name": "Valid BL - PDF-based Receipt (NYC221)",
            "subject": "Payment Confirmation - NYC221",
            "body": "Please find attached the payment receipt for BL NYC221.",
            "pdf": ("NYC221", 675.0, "receipt_nyc221.pdf")
        },
        3: {
            "name": "Valid BL - Mixed Content (NYC223)",
            "subject": "Payment for NYC223",
            "body": """
Payment confirmation for Bill of Lading NYC223.

Amount: $675.00
Date: August 1, 2025
Reference: NYC223-001

Receipt attached.
            """,
            "pdf": ("NYC223", 675.0, "receipt_nyc223.pdf")
        },
        4: {
            "name": "Invalid BL - Text-based (NYC224)",
            "subject": "Payment for NYC224",
            "body": "Payment of $500 for BL NYC224",
            "pdf": None
        },
        5: {
            "name": "Invalid BL - PDF-based (NYC225)",
            "subject": "Payment Receipt - NYC225",
            "body": "Payment receipt for BL NYC225 attached.",
            "pdf": ("NYC225", 600.0, "receipt_nyc225.pdf")
        },
        6: {
            "name": "Underpayment - Valid BL (NYC220)",
            "subject": "Partial Payment - NYC220",
            "body": "Partial payment of $650 for BL NYC220",
            "pdf": None
        },
        7: {
            "name": "Overpayment - Valid BL (NYC221)",
            "subject": "Overpayment - NYC221",
            "body": "Payment of $700 for BL NYC221 (includes extra amount)",
            "pdf": ("NYC221", 700.0, "receipt_nyc221_overpayment.pdf")
        },
        8: {
            "name": "Multiple BLs in One Email",
            "subject": "Bulk Payment - Multiple BLs",
            "body": """
Bulk payment for multiple bills:

BL NYC220: $700
BL NYC221: $675

Total: $1,375
            """,
            "pdf": None
        }
    }
    
    if test_number not in test_scenarios:
        print(f"❌ Test number {test_number} not found. Available tests: 1-8")
        return
    
    test = test_scenarios[test_number]
    print(f"📧 Sending Test {test_number}: {test['name']}")
    print("-" * 50)
    
    if test['pdf']:
        bl_number, amount, filename = test['pdf']
        pdf_content = create_real_pdf_receipt(bl_number, amount)
        send_email_with_pdf(target_email, test['subject'], test['body'], pdf_content, filename)
    else:
        send_text_only_email(target_email, test['subject'], test['body'])

def show_email_config():
    """Show current email configuration"""
    print("📧 Email Configuration Status")
    print("=" * 50)
    print(f"SMTP Server: {EmailConfig.SMTP_SERVER or '❌ Not set'}")
    print(f"SMTP Port: {EmailConfig.SMTP_PORT or '❌ Not set'}")
    print(f"SMTP Username: {EmailConfig.SMTP_USERNAME or '❌ Not set'}")
    print(f"SMTP Password: {'✅ Set' if EmailConfig.SMTP_PASSWORD else '❌ Not set'}")
    print(f"From Email: {EmailConfig.FROM_EMAIL or '❌ Not set'}")
    
    if all([EmailConfig.SMTP_SERVER, EmailConfig.SMTP_PORT, EmailConfig.SMTP_USERNAME, EmailConfig.SMTP_PASSWORD, EmailConfig.FROM_EMAIL]):
        print("\n✅ Email configuration is complete!")
    else:
        print("\n❌ Email configuration is incomplete!")
        print("Please check your .env.local file for the following variables:")
        print("  SMTP_SERVER, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, FROM_EMAIL")

if __name__ == "__main__":
    import sys
    
    print("📧 Real Email Testing System for Receipt Processing")
    print("=" * 70)
    
    # Show email configuration
    show_email_config()
    
    if len(sys.argv) < 2:
        print("\nUsage:")
        print("  python send_test_emails.py <target_email> [test_number]")
        print("\nExamples:")
        print("  python send_test_emails.py your-email@gmail.com")
        print("  python send_test_emails.py your-email@gmail.com 2")
        print("\nTest Numbers:")
        print("  1. Valid BL - Text-based (NYC220)")
        print("  2. Valid BL - PDF-based (NYC221)")
        print("  3. Valid BL - Mixed content (NYC223)")
        print("  4. Invalid BL - Text-based (NYC224)")
        print("  5. Invalid BL - PDF-based (NYC225)")
        print("  6. Underpayment - Valid BL (NYC220)")
        print("  7. Overpayment - Valid BL (NYC221)")
        print("  8. Multiple BLs in one email")
        sys.exit(1)
    
    target_email = sys.argv[1]
    test_number = int(sys.argv[2]) if len(sys.argv) > 2 else None
    
    if test_number:
        send_single_test_email(target_email, test_number)
    else:
        send_all_test_emails(target_email)