#!/usr/bin/env python3
"""
Setup script for local environment
Helps create .env.local file with proper database configuration
"""
import os
import sys

def create_env_local():
    """Create .env.local file with local development settings"""
    print("🔧 Setting up local environment file...")
    
    # Check if .env.local already exists
    if os.path.exists('.env.local'):
        print("⚠️  .env.local already exists!")
        response = input("Do you want to overwrite it? (y/N): ")
        if response.lower() != 'y':
            print("❌ Setup cancelled")
            return False
    
    # Get database credentials from user
    print("\n📊 Database Configuration")
    print("Enter your local PostgreSQL database credentials:")
    
    db_host = input("Database Host (default: localhost): ").strip() or "localhost"
    db_port = input("Database Port (default: 5432): ").strip() or "5432"
    db_name = input("Database Name (default: iqstrade_local): ").strip() or "iqstrade_local"
    db_user = input("Database User (default: postgres): ").strip() or "postgres"
    db_password = input("Database Password: ").strip()
    
    if not db_password:
        print("❌ Database password is required!")
        return False
    
    # Get other required settings
    print("\n🔑 Security Keys")
    jwt_secret = input("JWT Secret Key (default: local-jwt-secret-key): ").strip() or "local-jwt-secret-key"
    encryption_key = input("Encryption Key (default: local-encryption-key): ").strip() or "local-encryption-key"
    
    print("\n📧 Email Settings (optional for testing)")
    email_host = input("Email Host (default: imap.gmail.com): ").strip() or "imap.gmail.com"
    email_username = input("Email Username (optional): ").strip()
    email_password = input("Email Password (optional): ").strip()
    
    print("\n🤖 OpenAI Settings (optional for testing)")
    openai_key = input("OpenAI API Key (optional): ").strip()
    
    # Create .env.local content
    env_content = f"""# ========================================
# LOCAL DEVELOPMENT ENVIRONMENT VARIABLES
# Generated by setup_local_env.py
# ========================================

# === FLASK ENVIRONMENT ===
FLASK_ENV=local
FLASK_DEBUG=true

# === DATABASE (Local PostgreSQL) ===
DB_HOST={db_host}
DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}
DB_PORT={db_port}

# === SECURITY KEYS ===
JWT_SECRET_KEY={jwt_secret}
ENCRYPTION_KEY={encryption_key}

# === EMAIL SETTINGS ===
EMAIL_HOST={email_host}
EMAIL_USERNAME={email_username}
EMAIL_PASSWORD={email_password}
EMAIL_PORT=587

# SMTP Settings
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME={email_username}
SMTP_PASSWORD={email_password}
FROM_EMAIL={email_username}

# === OPENAI SETTINGS ===
OPENAI_API_KEY={openai_key}

# === CORS SETTINGS ===
ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:5000,http://127.0.0.1:5000

# === EMAIL SCHEDULER SETTINGS ===
EMAIL_CHECK_INTERVAL=900
AUTO_SEND_ENABLED=true
CONFIDENCE_THRESHOLD=0.8

# === LOGGING SETTINGS ===
LOG_LEVEL=DEBUG
ENABLE_EMAIL_LOGGING=true

# === FILE UPLOAD SETTINGS ===
MAX_EMAIL_SIZE=10485760
ALLOWED_ATTACHMENT_TYPES=pdf,jpg,jpeg,png

# === LOCAL DEVELOPMENT OVERRIDES ===
FORCE_HTTPS=0
JWT_COOKIE_SECURE=false
JWT_COOKIE_SAMESITE=Lax
"""
    
    # Write .env.local file
    try:
        with open('.env.local', 'w') as f:
            f.write(env_content)
        
        print(f"\n✅ .env.local created successfully!")
        print(f"📁 File location: {os.path.abspath('.env.local')}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error creating .env.local: {e}")
        return False

def test_database_connection():
    """Test the database connection with the new .env.local"""
    print("\n🧪 Testing database connection...")
    
    try:
        # Load the new .env.local
        from dotenv import load_dotenv
        load_dotenv('.env.local')
        
        # Test connection
        from config import get_db_conn
        conn = get_db_conn()
        
        if conn:
            print("✅ Database connection successful!")
            
            # Test a simple query
            cursor = conn.cursor()
            cursor.execute("SELECT version()")
            version = cursor.fetchone()[0]
            print(f"📊 PostgreSQL version: {version}")
            
            cursor.close()
            conn.close()
            return True
        else:
            print("❌ Database connection failed!")
            return False
            
    except Exception as e:
        print(f"❌ Database test failed: {e}")
        return False

def main():
    """Main setup function"""
    print("🚀 Local Environment Setup")
    print("=" * 50)
    
    # Create .env.local
    if not create_env_local():
        return
    
    # Test database connection
    if test_database_connection():
        print("\n🎉 Setup completed successfully!")
        print("\n💡 Next steps:")
        print("  1. Run: python test_email_with_attachments.py")
        print("  2. Start backend: python run_local.py")
        print("  3. Start frontend: npm start (in frontend directory)")
    else:
        print("\n⚠️  Setup completed but database connection failed.")
        print("💡 Please check your PostgreSQL installation and credentials.")

if __name__ == "__main__":
    main() 